# Generated by Django 4.2.3 on 2023-07-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Academia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("endereco", models.CharField(max_length=200)),
                ("telefone", models.CharField(max_length=200)),
                ("foto", models.ImageField(blank=True, null=True, upload_to="fotos")),
            ],
        ),
    ]
