# Generated by Django 4.2.3 on 2023-07-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smartfit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academia",
            name="foto",
            field=models.CharField(default="", max_length=300),
        ),
    ]
