# Generated by Django 4.2.3 on 2023-07-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smartfit", "0002_alter_academia_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="academia",
            name="plano",
            field=models.CharField(
                choices=[
                    ("plano1", "Mensal"),
                    ("plano2", "Semestral"),
                    ("plano3", "Anual"),
                ],
                default="Clique aqui e escolha seu plano",
                max_length=10,
            ),
        ),
    ]
