# Generated by Django 4.2.3 on 2023-07-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smartfit", "0003_academia_plano"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academia",
            name="endereco",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="academia",
            name="nome",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="academia",
            name="plano",
            field=models.CharField(
                choices=[
                    ("Mensal", "Mensal"),
                    ("Semestral", "Semestral"),
                    ("Anual", "Anual"),
                ],
                default="Clique aqui e escolha seu plano",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="academia",
            name="telefone",
            field=models.CharField(max_length=13),
        ),
    ]
