# Generated by Django 4.2.3 on 2023-07-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smartfit", "0004_alter_academia_endereco_alter_academia_nome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academia",
            name="nascimento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
