# Generated by Django 4.2.3 on 2023-07-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smartfit", "0006_alter_academia_plano_alter_academia_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academia",
            name="nome",
            field=models.CharField(default="asd", max_length=30),
        ),
        migrations.AlterField(
            model_name="academia",
            name="telefone",
            field=models.CharField(max_length=13),
        ),
    ]
