# Generated by Django 4.2.3 on 2023-07-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smartfit", "0007_alter_academia_nome_alter_academia_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academia",
            name="nome",
            field=models.CharField(max_length=30),
        ),
    ]
