# Generated by Django 4.2.3 on 2023-07-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smartfit", "0008_alter_academia_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academia",
            name="endereco",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="academia",
            name="telefone",
            field=models.CharField(max_length=15),
        ),
    ]
